if(NOT DEFINED INPUT_FILE)
  message(FATAL_ERROR "INPUT_FILE is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

file(SIZE "${INPUT_FILE}" OS1_INITRD_PAYLOAD_LENGTH_BYTES)
math(EXPR OS1_INITRD_PAYLOAD_SECTOR_COUNT
  "(${OS1_INITRD_PAYLOAD_LENGTH_BYTES} + 511) / 512")

file(WRITE "${OUTPUT_FILE}" "; Generated initrd payload constants for the BIOS loader.\n\n")
file(APPEND "${OUTPUT_FILE}" "%define INITRD_PAYLOAD_LENGTH_BYTES ${OS1_INITRD_PAYLOAD_LENGTH_BYTES}\n")
file(APPEND "${OUTPUT_FILE}" "%define INITRD_PAYLOAD_SECTOR_COUNT ${OS1_INITRD_PAYLOAD_SECTOR_COUNT}\n")