set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(OS1_TOOLCHAIN_CC NAMES x86_64-elf-gcc REQUIRED)
find_program(OS1_TOOLCHAIN_CXX NAMES x86_64-elf-g++ REQUIRED)
find_program(OS1_TOOLCHAIN_LD NAMES x86_64-elf-ld REQUIRED)
find_program(OS1_TOOLCHAIN_NASM NAMES nasm REQUIRED)

set(CMAKE_C_COMPILER "${OS1_TOOLCHAIN_CC}" CACHE FILEPATH "os1 C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${OS1_TOOLCHAIN_CXX}" CACHE FILEPATH "os1 C++ compiler" FORCE)
set(CMAKE_LINKER "${OS1_TOOLCHAIN_LD}" CACHE FILEPATH "os1 linker" FORCE)
set(CMAKE_ASM_NASM_COMPILER "${OS1_TOOLCHAIN_NASM}" CACHE FILEPATH "os1 NASM compiler" FORCE)
